# Generated by Django 3.1 on 2020-08-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='author_name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='shelf_name',
            new_name='shelf',
        ),
        migrations.RenameField(
            model_name='shelfmodel',
            old_name='shelf_name',
            new_name='name',
        ),
    ]
